%====================================================================================
% waste_incinerator_service description   
%====================================================================================
dispatch( activationCommand, activationCommand(N) ). %command that turns the incinerator on
event( endBurning, endBurning(N) ). %event generated by the incinerator when the burning process is terminated
dispatch( cmd, cmd(MOVE) ). %MOVE = a|d|l|r|h   
request( step, step(TIME) ).
reply( stepdone, stepdone(V) ).  %%for step
reply( stepfailed, stepfailed(DURATION,CAUSE) ).  %%for step
%====================================================================================
context(ctx_waste_incinerator_service, "localhost",  "TCP", "8125").
context(ctxbasicrobot, "127.0.0.1",  "TCP", "8120").
context(ctxrasp, "127.0.0.2",  "TCP", "8122").
 qactor( basicrobot, ctxbasicrobot, "external").
  qactor( wis, ctx_waste_incinerator_service, "it.unibo.wis.Wis").
 static(wis).
  qactor( incinerator, ctx_waste_incinerator_service, "it.unibo.incinerator.Incinerator").
 static(incinerator).
  qactor( monitoring_device, ctxrasp, "it.unibo.monitoring_device.Monitoring_device").
 static(monitoring_device).
