apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    "feature-gates": "InPlacePodVerticalScaling=true"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: "10.244.0.0/16" 
apiServer:
  extraArgs:
    feature-gates: "InPlacePodVerticalScaling=true"
controllerManager:
  extraArgs:
    feature-gates: "InPlacePodVerticalScaling=true"
scheduler:
  extraArgs:
    feature-gates: "InPlacePodVerticalScaling=true"
