/* Generated by AN DISI Unibo */ 
package it.unibo.oprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024
import unibo.planner23.*

class Oprobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
			
				var planner     = Planner23Util()
				planner.initAI()
				planner.loadRoomMap("mapCompleteWithObst23ok")
				var HOMEx = 0
				var HOMEy = 0
				var WASTEINx = 0
				var WASTEINy = 4
				var BURNINx = 3
				var BURNINy = 2
				var BURNOUTx = 4
				var BURNOUTy = 3
				var ASHOUTx = 6
				var ASHOUTy = 4
				planner.setGoal(HOMEx,HOMEy)
				var CurPlan = planner.doPlanCompact()
				fun updateCurPlan(x:Int, y:Int){
					planner.setGoal(x,y)
					CurPlan = planner.doPlanCompact()
					planner.doPathOnMap(CurPlan)
				}
				
				var rpReady=false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name STARTS")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engage", cond=doswitch() )
				}	 
				state("engage") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | $MyName engaging ... ")
						request("engage", "engage($MyName,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engage", 
				 	 					  scope, context!!, "local_tout_"+name+"_engage", 1000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t05",targetState="noResponse",cond=whenTimeout("local_tout_"+name+"_engage"))   
					transition(edgeName="t06",targetState="waitingWorking",cond=whenReply("engagedone"))
					transition(edgeName="t07",targetState="end",cond=whenReply("engagerefused"))
				}	 
				state("noResponse") { //this:State
					action { //it:State
						CommUtils.outyellow("BasicRobot did not answer!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="end", cond=doswitch() )
				}	 
				state("waitingWorking") { //this:State
					action { //it:State
						 
									if (!rpReady){
										planner.doPathOnMap(CurPlan)
									}  else {
										rpReady = false
									}
						CommUtils.outyellow("$name is in HOME position waiting for working")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="takeRP",cond=whenDispatch("arrived_RP"))
				}	 
				state("takeRP") { //this:State
					action { //it:State
						CommUtils.outyellow("OpRobot is going to take an RP..")
						
									updateCurPlan(WASTEINx,WASTEINy)
						if(CurPlan!="") 
						request("doplan", "doplan($CurPlan,330)" ,"basicrobot" )  
						else 
						forward("cmd", "cmd(d)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="bringRPtoBURNIN",cond=whenReply("doplandone"))
					transition(edgeName="t010",targetState="exit",cond=whenReply("doplanfailed"))
					transition(edgeName="t011",targetState="bringRPtoBURNIN",cond=whenDispatch("cmd"))
				}	 
				state("bringRPtoBURNIN") { //this:State
					action { //it:State
						delay(2000) 
						
									updateCurPlan(BURNINx,BURNINy) 
						request("doplan", "doplan($CurPlan,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="returnHOME",cond=whenReply("doplandone"))
					transition(edgeName="t013",targetState="exit",cond=whenReply("doplanfailed"))
				}	 
				state("returnHOME") { //this:State
					action { //it:State
						delay(2000) 
						forward("rpInBurnin", "rpInBurnin(1)" ,"wis" ) 
						CommUtils.outyellow("An RP is in BURNIN port")
						
									updateCurPlan(HOMEx,HOMEy)
						request("doplan", "doplan($CurPlan,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="waitingForIncinerator",cond=whenReply("doplandone"))
					transition(edgeName="t015",targetState="exit",cond=whenReply("doplanfailed"))
				}	 
				state("waitingForIncinerator") { //this:State
					action { //it:State
						CommUtils.outyellow("Waiting for incinerator to finish its job")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="takeAshFromBURNOUT",cond=whenEvent("endBurning"))
				}	 
				state("takeAshFromBURNOUT") { //this:State
					action { //it:State
						
									updateCurPlan(BURNOUTx,BURNOUTy)
						request("doplan", "doplan($CurPlan,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="bringAshtoASHOUT",cond=whenReply("doplandone"))
					transition(edgeName="t018",targetState="exit",cond=whenReply("doplanfailed"))
				}	 
				state("bringAshtoASHOUT") { //this:State
					action { //it:State
						delay(2000) 
						
									updateCurPlan(ASHOUTx,ASHOUTy)
						request("doplan", "doplan($CurPlan,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="restartJob",cond=whenReply("doplandone"))
					transition(edgeName="t020",targetState="exit",cond=whenReply("doplanfailed"))
				}	 
				state("restartJob") { //this:State
					action { //it:State
						delay(2000) 
						CommUtils.outyellow("The ash has been taken out")
						forward("newAshes", "newAshes(1)" ,"monitoring_device_mok" ) 
						
									planner.setGoal(HOMEx,HOMEy)
									CurPlan = planner.doPlanCompact()
						request("doplan", "doplan($CurPlan,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="takeRpBeforeFinishPlan",cond=whenDispatch("arrived_RP"))
					transition(edgeName="t022",targetState="waitingWorking",cond=whenReply("doplandone"))
					transition(edgeName="t023",targetState="exit",cond=whenReply("doplanfailed"))
				}	 
				state("takeRpBeforeFinishPlan") { //this:State
					action { //it:State
						CommUtils.outyellow("A new RP has arrived before OpRobot returned HOME")
						rpReady=true 
						emit("alarm", "alarm(X)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="handlePlanDone",cond=whenReply("doplandone"))
					transition(edgeName="t025",targetState="handlePlanFailed",cond=whenReply("doplanfailed"))
				}	 
				state("handlePlanFailed") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("doplanfailed(ARG)"), Term.createTerm("doplanfailed(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var Plan = payloadArg(0).toString()
												var PlanDone = CurPlan.substring(0,(CurPlan.length - Plan.length)) 
								planner.doPathOnMap(PlanDone) 
						}
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="takeRP", cond=doswitch() )
				}	 
				state("handlePlanDone") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						planner.doPathOnMap(CurPlan) 
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="takeRP", cond=doswitch() )
				}	 
				state("end") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | ENDS ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("exit") { //this:State
					action { //it:State
						CommUtils.outyellow("$name has been terminated")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
