/* Generated by AN DISI Unibo */ 
package it.unibo.wismonitoringdeviceproxy

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Wismonitoringdeviceproxy ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var timeoutExpired = true;
				var Status = 0;
				var previousStatus = 0;
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://localhost:8081", "wismonitoringdeviceproxynat" )
						CommUtils.outcyan("$name | CREATED  (and connected to mosquitto) ... ")
						delay(1000) 
						subscribe(  "wisinfo" ) //mqtt.subscribe(this,topic)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_wait", 
				 	 					  scope, context!!, "local_tout_"+name+"_wait", 15000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t02",targetState="handleTimeoutExpired",cond=whenTimeout("local_tout_"+name+"_wait"))   
					transition(edgeName="t03",targetState="handleUpdateStatoAshStorage",cond=whenEvent("statoAshStorage"))
				}	 
				state("handleUpdateStatoAshStorage") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("statoAshStorage(N)"), Term.createTerm("statoAshStorage(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												if(timeoutExpired){
													timeoutExpired = false
								forward("monitoringDeviceRuns", "monitoringDeviceRuns(1)" ,"wis" ) 
								
												}
												try{
													var Status = payloadArg(0).toInt()
								if( Status>=0 && Status != previousStatus 
								 ){forward("ashesLevel", "ashesLevel($Status)" ,"wis" ) 
								}
									
												previousStatus=Status
												}catch(e:Exception){
								CommUtils.outred("$name received invalid payload:${payloadArg(0)}")
								
												}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("handleTimeoutExpired") { //this:State
					action { //it:State
						timeoutExpired = true 
						forward("monitoringDeviceRuns", "monitoringDeviceRuns(0)" ,"wis" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
} 
