/* Generated by AN DISI Unibo */ 
package it.unibo.monitoringdevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Monitoringdevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var levelAshStorage = 0;
				var IncineratorStatus = 0;
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(2000) 
						CommUtils.outblack("$name STARTS")
						subscribeToLocalActor("datacleaner") 
						forward("statoAshStorage", "statoAshStorage(0)" ,"wis" ) 
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						CommUtils.outblue("$name Waiting data from sonar or updates from Incinerator...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleUpdateStatoIncinerator",cond=whenDispatch("statoIncinerator"))
					transition(edgeName="t03",targetState="handleAshStorageLevel",cond=whenEvent("ashStorageLevel"))
				}	 
				state("handleUpdateStatoIncinerator") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("statoIncinerator(N)"), Term.createTerm("statoIncinerator(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
									      		IncineratorStatus = payloadArg(0).toInt() 
								CommUtils.outblue("$name Current incinerator state: $IncineratorStatus")
								if( IncineratorStatus==1 
								 ){forward("led_on", "led_on(1)" ,"led" ) 
								}
								else
								 {if( levelAshStorage==1 
								  ){forward("led_off", "led_off(1)" ,"led" ) 
								 }
								 else
								  {forward("led_blink", "led_blink(1)" ,"led" ) 
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("handleAshStorageLevel") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ashStorageLevel(D)"), Term.createTerm("ashStorageLevel(L)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												levelAshStorage = payloadArg(0).toInt()
								CommUtils.outblue("$name current AshStorageLevel=$levelAshStorage")
								if( IncineratorStatus==0 
								 ){if( levelAshStorage==1 
								 ){forward("led_off", "led_off(1)" ,"led" ) 
								}
								else
								 {forward("led_blink", "led_blink(1)" ,"led" ) 
								 }
								}
								if( levelAshStorage==2 
								 ){CommUtils.outblue("$name Updating AshStorageStatus to 1")
								forward("statoAshStorage", "statoAshStorage(1)" ,"wis" ) 
								}
								else
								 {CommUtils.outblue("$name Updating AshStorageStatus to 0")
								 forward("statoAshStorage", "statoAshStorage(0)" ,"wis" ) 
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
} 
