FROM alpine:latest
COPY ./unibolibs/*.jar /unibolibs/
RUN apk update 
RUN apk add --no-cache openjdk11-jdk
RUN apk add --no-cache mosquitto mosquitto-clients
RUN wget https://services.gradle.org/distributions/gradle-8.6-bin.zip -P /tmp
RUN unzip /tmp/gradle-8.6-bin.zip -d /opt
RUN ln -s /opt/gradle-8.6/bin/gradle /usr/local/bin/gradle
RUN echo 'export GRADLE_HOME=/opt/gradle-8.6' >> ~/.bashrc
RUN echo 'export PATH=$PATH:$GRADLE_HOME/bin' >> ~/.bashrc
RUN source ~/.bashrc