/* Generated by AN DISI Unibo */ 
package it.unibo.scale

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Scale ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var RPs = 0;
				var previous_RPs = 0; 
				val WRP = 100;
				var timeLastUpdate = System.currentTimeMillis();
				var timeout = 10000;
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						subscribeToLocalActor("scaledevice") 
						CommUtils.outblue("$name subscribed to scaledevice")
						connectToMqttBroker( "tcp://localhost:8081", "scalenat" )
						CommUtils.outblue("$name | CREATED  (and connected to mosquitto) ... ")
						subscribe(  "wisinfo" ) //mqtt.subscribe(this,topic)
						//val m = MsgUtil.buildEvent(name, "new_RP", "new_RP(0)" ) 
						publish(MsgUtil.buildEvent(name,"new_RP","new_RP(0)").toString(), "wisinfo" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="filter",cond=whenEvent("scaledata"))
				}	 
				state("filter") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("weight(W)"), Term.createTerm("weight(W)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  
									      		var W = payloadArg(0).toInt() 
									      		RPs = (W/WRP).toInt()
								if( RPs > previous_RPs 
								 ){CommUtils.outmagenta("$name emit number of RPs=$RPs in Waste Storage")
								
									      			for (i in previous_RPs..RPs-1) {
								//val m = MsgUtil.buildEvent(name, "new_RP", "new_RP(1)" ) 
								publish(MsgUtil.buildEvent(name,"new_RP","new_RP(1)").toString(), "wisinfo" )   
								
									      			}
									      			timeLastUpdate = System.currentTimeMillis()
								}
								if( System.currentTimeMillis()-timeLastUpdate>=10000 
								 ){//val m = MsgUtil.buildEvent(name, "new_RP", "new_RP(0)" ) 
								publish(MsgUtil.buildEvent(name,"new_RP","new_RP(0)").toString(), "wisinfo" )   
								timeLastUpdate=System.currentTimeMillis() 
								}
								 previous_RPs = RPs;  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="filter",cond=whenEvent("scaledata"))
				}	 
			}
		}
} 
