/* Generated by AN DISI Unibo */ 
package it.unibo.wis

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Wis ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var RP = 0 ; var statoIncinerator = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(500) 
						CommUtils.outblack("$name STARTS")
						forward("activationCommand", "activationCommand(1)" ,"incinerator" ) 
						observeResource("localhost","8125","ctx_waste_incinerator_service","incinerator","statoIncinerator")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingRP", cond=doswitch() )
				}	 
				state("waitingRP") { //this:State
					action { //it:State
						CommUtils.outblack("Waiting new RP...")
						delay(10000) 
						forward("arrived_RP", "arrived_RP(1)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleEndBurning",cond=whenEvent("endBurning"))
					transition(edgeName="t01",targetState="handleUpdateStatoIncinerator",cond=whenDispatch("statoIncinerator"))
					transition(edgeName="t02",targetState="handleRP",cond=whenDispatch("arrived_RP"))
				}	 
				state("handleRP") { //this:State
					action { //it:State
						CommUtils.outblack("New RP is arrived")
						 RP++  
						if(  statoIncinerator == 0 && RP >= 1  
						 ){forward("startBurning", "startBurning(1)" ,"incinerator" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingRP", cond=doswitch() )
				}	 
				state("handleUpdateStatoIncinerator") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("statoIncinerator(N)"), Term.createTerm("statoIncinerator(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 statoIncinerator = payloadArg(0).toInt()  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingRP", cond=doswitch() )
				}	 
				state("handleEndBurning") { //this:State
					action { //it:State
						CommUtils.outblack("Incinerator has finished to burn")
						 statoIncinerator = 0  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingRP", cond=doswitch() )
				}	 
			}
		}
} 
