version: '3.8'
services:
  scale:
    image: dagus01/scale:arm 
    privileged: true
    ports:
      - "8200:8200"  
    secrets:
      - source: client_crt
        target: /etc/stunnel/certs/client.crt
      - source: client_key
        target: /etc/stunnel/certs/client.key
      - source: ca_crt
        target: /etc/stunnel/certs/ca.crt 
    volumes:
      - ./stunnel_raspberry.conf:/etc/stunnel/stunnel.conf
      - ./scale_conf.json:/scale-1.0/bin/scale_conf.json
    command: ["sh", "-c", "sleep 10 && stunnel && ./scale"]
   
  monitoringdevice:
    image: dagus01/monitoringdevice:arm 
    privileged: true
    ports:
      - "8100:8100"  
    secrets:
      - source: client_crt
        target: /etc/stunnel/certs/client.crt
      - source: client_key
        target: /etc/stunnel/certs/client.key
      - source: ca_crt
        target: /etc/stunnel/certs/ca.crt
    volumes:
      - ./stunnel_raspberry.conf:/etc/stunnel/stunnel.conf
      - ./monitoringdevice_conf.json:/monitoringdevice-1.0/bin/monitoringdevice_conf.json
    command: ["sh", "-c", "sleep 10 && stunnel && ./monitoringdevice"]
