version: '3.8'
services:
  wis:
    image: wis:1.0 
    ports:
      - "8125:8125"  
    depends_on:
      - basicrobot
      - wis_broker
    networks:
      - wis_LAN  
    volumes:
      - ./ca.crt:/etc/stunnel/certs/ca.crt
      - ./client.crt:/etc/stunnel/certs/client.crt
      - ./client.key:/etc/stunnel/certs/client.key
      - ./stunnel_wis.conf:/etc/stunnel/stunnel_wis.conf
      - ./wis_conf.json:/wis_conf.json
    command: ["sh", "-c", "sleep 10 && stunnel /etc/stunnel/stunnel_wis.conf && ./waste_incinerator_service"]

  basicrobot:
    image: basicrobot24:1.0
    ports:
      - "8020:8020" 
      - "8085:8085"
    networks:
      - wis_LAN 
    depends_on:
      - wenv
    volumes:
      - ./basicrobotConfig.json:/basicrobot24-1.0/bin/basicrobotConfig.json
      - ./ca.crt:/etc/stunnel/certs/ca.crt
      - ./basicrobot.crt:/etc/stunnel/certs/basicrobot.crt
      - ./basicrobot.key:/etc/stunnel/certs/basicrobot.key
      - ./stunnel_basicrobot.conf:/etc/stunnel/stunnel_basicrobot.conf       
    command: ["sh", "-c", "sleep 5 && stunnel /etc/stunnel/stunnel_basicrobot.conf && ./basicrobot24"]

  wis_facade:
    image: wisfacade:1.0
    ports:
      - "8080:8080"
    depends_on:
      - wis_broker
    networks:
      - wis_LAN
    volumes:
      - ./ca.crt:/etc/stunnel/certs/ca.crt
      - ./client.crt:/etc/stunnel/certs/client.crt
      - ./client.key:/etc/stunnel/certs/client.key
      - ./stunnel_wisfacade.conf:/etc/stunnel/stunnel_wisfacade.conf
      - ./facadeConfig.json:/facadeConfig.json
    command: ["sh", "-c", "sleep 5 && stunnel /etc/stunnel/stunnel_wisfacade.conf && java -jar ./wisFacade-0.0.1-SNAPSHOT.jar"]

  wis_broker:
    image: mqtt_broker:1.0
    ports:
      - "8081:8081"
    networks:
      - wis_LAN
    volumes:
      - ./ca.crt:/etc/mosquitto/certs/ca.crt
      - ./server.crt:/etc/mosquitto/certs/server.crt
      - ./server.key:/etc/mosquitto/certs/server.key
      - ./mosquitto.conf:/etc/mosquitto/mosquitto.conf
    command: ["mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]

  wenv:
    image: docker.io/natbodocker/virtualrobotdisi23:1.0
    ports:
      - 8090:8090
      - 8091:8091
    networks:
      - wis_LAN

networks:
  wis_LAN: