/* Generated by AN DISI Unibo */ 
package it.unibo.wis

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Wis ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var AshStorageStatus = 0 
				var RPs = 0
				var monitoringDeviceRunning = 1
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outgreen("$name STARTS")
						forward("activationCommand", "activationCommand(1)" ,"incinerator" ) 
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingRP", cond=doswitchGuarded({monitoringDeviceRunning!=0 
					}) )
					transition( edgeName="goto",targetState="waitForMonitoringDeviceToRun", cond=doswitchGuarded({! (monitoringDeviceRunning!=0 
					) }) )
				}	 
				state("waitingRP") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="handleMonitoringDeviceRunningStatus",cond=whenDispatch("monitoringDeviceRuns"))
					transition(edgeName="t05",targetState="handleUpdateAshesLevel",cond=whenDispatch("ashesLevel"))
					transition(edgeName="t06",targetState="handleRP",cond=whenDispatch("arrived_RP"))
				}	 
				state("handleMonitoringDeviceRunningStatus") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("monitoringDeviceRuns(N)"), Term.createTerm("monitoringDeviceRuns(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								monitoringDeviceRunning=payloadArg(0).toInt() 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleMonitoringDeviceRunningStatus", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleMonitoringDeviceRunningStatus", 1000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t07",targetState="ackMonitoringDeviceRunningStatus",cond=whenTimeout("local_tout_"+name+"_handleMonitoringDeviceRunningStatus"))   
					transition(edgeName="t08",targetState="handleMonitoringDeviceRunningStatus",cond=whenDispatch("monitoringDeviceRuns"))
				}	 
				state("ackMonitoringDeviceRunningStatus") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitForMonitoringDeviceToRun", cond=doswitchGuarded({monitoringDeviceRunning==0 
					}) )
					transition( edgeName="goto",targetState="waitingRP", cond=doswitchGuarded({! (monitoringDeviceRunning==0 
					) }) )
				}	 
				state("waitForMonitoringDeviceToRun") { //this:State
					action { //it:State
						CommUtils.outred("$name waiting for monitoringDevice to run")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="handleMonitoringDeviceRunningStatus",cond=whenDispatch("monitoringDeviceRuns"))
				}	 
				state("handleRP") { //this:State
					action { //it:State
						CommUtils.outgreen("New RP is arrived")
						forward("arrived_RP", "arrived_RP(1)" ,"oprobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="handleRPInBurnin",cond=whenDispatch("rpInBurnin"))
				}	 
				state("handleRPInBurnin") { //this:State
					action { //it:State
						CommUtils.outgreen("An RP is ready to be burnt")
						forward("startBurning", "startBurning(1)" ,"incinerator" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="handleEndBurning",cond=whenEvent("endBurning"))
				}	 
				state("handleEndBurning") { //this:State
					action { //it:State
						CommUtils.outgreen("Incinerator has finished to burn")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="endRoute",cond=whenDispatch("newAshes"))
				}	 
				state("endRoute") { //this:State
					action { //it:State
						CommUtils.outgreen("$name OpRobot has finished its route")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_endRoute", 
				 	 					  scope, context!!, "local_tout_"+name+"_endRoute", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t013",targetState="waitingRP",cond=whenTimeout("local_tout_"+name+"_endRoute"))   
					transition(edgeName="t014",targetState="handleUpdateAshesLevel",cond=whenDispatch("ashesLevel"))
				}	 
				state("handleUpdateAshesLevel") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("ashesLevel(N)"), Term.createTerm("ashesLevel(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 AshStorageStatus = payloadArg(0).toInt() 
								CommUtils.outgreen("AshStorageStatus: $AshStorageStatus")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleUpdateAshesLevel", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleUpdateAshesLevel", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t015",targetState="ashCheckFinish",cond=whenTimeout("local_tout_"+name+"_handleUpdateAshesLevel"))   
					transition(edgeName="t016",targetState="handleUpdateAshesLevel",cond=whenDispatch("ashesLevel"))
				}	 
				state("ashCheckFinish") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingRP", cond=doswitchGuarded({ AshStorageStatus == 0  
					}) )
					transition( edgeName="goto",targetState="waitingAshesToBeRemoved", cond=doswitchGuarded({! ( AshStorageStatus == 0  
					) }) )
				}	 
				state("waitingAshesToBeRemoved") { //this:State
					action { //it:State
						CommUtils.outgreen("WIS is waiting for an operator to remove ashes in AshStorage...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="handleUpdateAshesLevel",cond=whenDispatch("ashesLevel"))
				}	 
			}
		}
} 
