version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi23:1.0
    ports:
      - 8090:8090 
      - 8091:8091/tcp
      - 8091:8091/udp
    network_mode: "host"
  basicrobot24:
    #image: basicrobot24:1.0
    image: docker.io/natbodocker/basicrobot24:1.0 
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
      - 8085:8085
    network_mode: "host"
    depends_on:
      - wenv
 

## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f webbasicrobot24.yaml  up
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv